version: "3.8"

services:
  frontend-container:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_BASE_URL=http://localhost:8000/api
    image: frontend-image
    container_name: frontend-container
    ports:
      - 3000:3000
    environment:
      - REACT_APP_BACKEND_BASE_URL=http://localhost:8000/api

  backend-container:
    build:
      context: ./backend/app
      dockerfile: Dockerfile
    image: backend-image
    container_name: backend-container
    ports:
      - 8000:8000
    command: gunicorn -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000 --timeout 480 main:app
    volumes:
      - ./logs:/app/logs
