version: "3.8"

services:
  diet-code-frontend-container:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: diet-code-frontend-image
    container_name: diet-code-frontend-container
    ports:
      - 3000:3000
    command: ["npm", "start"]
    environment:
      - REACT_APP_BACKEND_BASE_URL=http://localhost:8000

  diet-code-backend-container:
    build:
      context: ./backend/app
      dockerfile: Dockerfile
    image: diet-code-backend-image
    container_name: diet-code-backend-container
    ports:
      - 8000:8000
    command: gunicorn -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000 --timeout 480 main:app
