version: "3.8"

services:
  diet-code-backend-container:
    build:
      context: ./backend/app
      dockerfile: Dockerfile
    command: gunicorn -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000 --timeout 480 main:app
    image: diet-code-backend-image
    container_name: diet-code-backend-container
    ports:
      - 8000:8000
